// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ6Nr7Pyr7abpeSd8PPP-DMVW1JAYDXMY',
    appId: '1:69037549587:android:899f9acbe84c0e73bdb7e6',
    messagingSenderId: '69037549587',
    projectId: 'capstone-prod-39d16',
    storageBucket: 'capstone-prod-39d16.firebasestorage.app',
    androidClientId: '69037549587-t5b3rc0kacjk2039dt784v032l5ph64j.apps.googleusercontent.com', // ← 추가
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH0d47FjsYXeNdUl4z4hG6d4PGghVEUX8',
    appId: '1:69037549587:ios:027b7bdd8a9481f5bdb7e6',
    messagingSenderId: '69037549587',
    projectId: 'capstone-prod-39d16',
    storageBucket: 'capstone-prod-39d16.firebasestorage.app',
    iosBundleId: 'com.example.nihongo',
  );
}
