// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw2WX4U6sSEmnSFVfOFGK-ku2FihhhtUU',
    appId: '1:113939685128:android:6024b531e1d1a1774956bd',
    messagingSenderId: '113939685128',
    projectId: 'capstone-ee1db',
    storageBucket: 'capstone-ee1db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiScvQ2bPO2v3CeUqxk-jbFzoctz8eGUM',
    appId: '1:113939685128:ios:d3446fecf8cdcb064956bd',
    messagingSenderId: '113939685128',
    projectId: 'capstone-ee1db',
    storageBucket: 'capstone-ee1db.firebasestorage.app',
    androidClientId: '113939685128-22ohkuc50695emcdglsgth52n8gh42kf.apps.googleusercontent.com',
    iosClientId: '113939685128-l9qqd15frlpr6o16qn80h8k8ogng8dg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.nihongo',
  );

}